// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTaZ4Ul-WZ3nMVWZY0btlUUzvtkLsrUL8',
    appId: '1:946435473744:web:063c216a7b357abe266c55',
    messagingSenderId: '946435473744',
    projectId: 'login-application-3f301',
    authDomain: 'login-application-3f301.firebaseapp.com',
    storageBucket: 'login-application-3f301.firebasestorage.app',
    measurementId: 'G-J2DQBT5GE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtFJqxke5swR3yQqnAXs8aSorn92K0RHA',
    appId: '1:946435473744:android:6f2e858206f085e0266c55',
    messagingSenderId: '946435473744',
    projectId: 'login-application-3f301',
    storageBucket: 'login-application-3f301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqO1M-qCF9WTDXX1Ra6IffQj2nJm_N7EU',
    appId: '1:946435473744:ios:5517542de6a74a06266c55',
    messagingSenderId: '946435473744',
    projectId: 'login-application-3f301',
    storageBucket: 'login-application-3f301.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqO1M-qCF9WTDXX1Ra6IffQj2nJm_N7EU',
    appId: '1:946435473744:ios:5517542de6a74a06266c55',
    messagingSenderId: '946435473744',
    projectId: 'login-application-3f301',
    storageBucket: 'login-application-3f301.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTaZ4Ul-WZ3nMVWZY0btlUUzvtkLsrUL8',
    appId: '1:946435473744:web:6c0528e062aa0857266c55',
    messagingSenderId: '946435473744',
    projectId: 'login-application-3f301',
    authDomain: 'login-application-3f301.firebaseapp.com',
    storageBucket: 'login-application-3f301.firebasestorage.app',
    measurementId: 'G-B3TKQ613XN',
  );
}
